### ISSUE TITLE
no NVIDIA GPU device is present!

### ISSUE THREAD

**Issue by mrahimpour** [Kamnitsask/deepmedic#128]
Hi, 

Thanks for sharing your code. I am trying to run your deepMedic code written by tensorflow on a server including several NVIDIA GPUs.  When I submit the job to run the code, I get the following error: 

​
2018-09-10 16:52:28.550802: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 AVX51$
2018-09-10 16:52:29.739483: E tensorflow/stream_executor/cuda/cuda_driver.cc:397] failed call to cuInit: CUDA_ERROR_NO_DEVICE
2018-09-10 16:52:29.739595: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:152] no NVIDIA GPU device is present: /dev/nvidia0 does not exist

I am working with python 3.6 and tensorflow 1.9.​ I will be grateful for any debugging advice or other insight.

**Comment by mrahimpour** [comment]
I found the reason; it was a mistake in setting CUDA; You can delete this issue, since I think it won't help the others in anyway!

Thanks again

**Comment by hyliu1989** [comment]
@mrahimpour would you mind to tell me what is the mistake you made? I found the same error.

**Comment by mrahimpour** [comment]
@hyliu1989 :  My mistake was setting  DEF_DEV_PROC as ARG_CPU_PROC instead of ARG_GPU_PROC.
